# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/userdata/k64D/trungpd_64d/vivado_work/test/srctest/source/zcu106/lab4_test/fir_test/FIR/FIR.srcs/sources_1/bd/design_audio/ip/design_audio_fir_0_0/design_audio_fir_0_0.xci
# IP: The module: 'design_audio_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/userdata/k64D/trungpd_64d/vivado_work/test/srctest/source/zcu106/lab4_test/fir_test/FIR/FIR.gen/sources_1/bd/design_audio/ip/design_audio_fir_0_0/constraints/fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_audio_fir_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/userdata/k64D/trungpd_64d/vivado_work/test/srctest/source/zcu106/lab4_test/fir_test/FIR/FIR.srcs/sources_1/bd/design_audio/ip/design_audio_fir_0_0/design_audio_fir_0_0.xci
# IP: The module: 'design_audio_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/userdata/k64D/trungpd_64d/vivado_work/test/srctest/source/zcu106/lab4_test/fir_test/FIR/FIR.gen/sources_1/bd/design_audio/ip/design_audio_fir_0_0/constraints/fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_audio_fir_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
