# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zcu106_audio_const.xdc

# Block Designs: bd/design_audio/design_audio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio || ORIG_REF_NAME==design_audio} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_zynq_ultra_ps_e_0_0/design_audio_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_audio_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_clk_wiz_0_0/design_audio_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_clk_wiz_0_0 || ORIG_REF_NAME==design_audio_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_proc_sys_reset_0_0/design_audio_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_proc_sys_reset_0_0 || ORIG_REF_NAME==design_audio_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_audio_formatter_0_0/design_audio_audio_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_audio_formatter_0_0 || ORIG_REF_NAME==design_audio_audio_formatter_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_xbar_0/design_audio_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_xbar_0 || ORIG_REF_NAME==design_audio_xbar_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_auto_pc_0/design_audio_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_auto_pc_0 || ORIG_REF_NAME==design_audio_auto_pc_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_ps8_0_axi_periph_0/design_audio_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_audio_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_rst_clk_wiz_0_48M_0/design_audio_rst_clk_wiz_0_48M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_rst_clk_wiz_0_48M_0 || ORIG_REF_NAME==design_audio_rst_clk_wiz_0_48M_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_axi_smc_0/design_audio_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_axi_smc_0 || ORIG_REF_NAME==design_audio_axi_smc_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_proc_sys_reset_1_0/design_audio_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_proc_sys_reset_1_0 || ORIG_REF_NAME==design_audio_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_i2s_transmitter_0_0/design_audio_i2s_transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_i2s_transmitter_0_0 || ORIG_REF_NAME==design_audio_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_i2s_receiver_0_0/design_audio_i2s_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_i2s_receiver_0_0 || ORIG_REF_NAME==design_audio_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_xlconcat_0_0/design_audio_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_xlconcat_0_0 || ORIG_REF_NAME==design_audio_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_axi_iic_0_0/design_audio_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_axi_iic_0_0 || ORIG_REF_NAME==design_audio_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_fir_0_0/design_audio_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_fir_0_0 || ORIG_REF_NAME==design_audio_fir_0_0} -quiet] -quiet

# IP: bd/design_audio/ip/design_audio_fir_1_0/design_audio_fir_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_audio_fir_1_0 || ORIG_REF_NAME==design_audio_fir_1_0} -quiet] -quiet

# XDC: /home/userdata/k64D/trungpd_64d/vivado_work/test/srctest/source/zcu106/lab4_test/fir_test/FIR/FIR.gen/sources_1/bd/design_audio/design_audio_ooc.xdc
